services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppasskuat
      MYSQL_ROOT_PASSWORD: rootpasskuat
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:php8.3-apache
    depends_on:
      - db
    ports:
      - "8089:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppasskuat
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins

  wpcli:
    image: wordpress:cli
    depends_on:
      - db
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppasskuat
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins

volumes:
  db_data:
  wp_data:
